TOKEN = MTUxMDUxODQyMTQ0MjQwMDMyNg.GBr_NL.zhfMMu9tklPZd8dhO2vX6pOf2hxDP5WTzlVPrs
API_KEY = ""
MAILSLURP_API_KEY=sk_ssW1YNXxLOSVZMly_sO57GpQMnjOSn7zgByTUUo98PTPZDZKpPA0gL2AhOJ0yX8yT6L7f4h8iXXo53LqS

#Dont Fill These In
LastUsedEmail=""
LastUserName=""
LastRecoveryCode=""
AUTHVALUE=""
