TOKEN = MTUxMDUxODQyMTQ0MjQwMDMyNg.GSVK1W.BS6YU2ywJYAlGDFQdLhP42lKQZjh_Fd1m_163k
API_KEY = ""
MAILSLURP_API_KEY=sk_ssW1YNXxLOSVZMly_sO57GpQMnjOSn7zgByTUUo98PTPZDZKpPA0gL2AhOJ0yX8yT6L7f4h8iXXo53LqS

#Dont Fill These In
LastUsedEmail=""
LastUserName=""
LastRecoveryCode=""
AUTHVALUE=""
